require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AboutPagesController do

  # This should return the minimal set of attributes required to create a valid
  # AboutPage. As you add validations to AboutPage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AboutPagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all about_pages as @about_pages" do
      about_page = AboutPage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:about_pages)).to eq([about_page])
    end
  end

  describe "GET show" do
    it "assigns the requested about_page as @about_page" do
      about_page = AboutPage.create! valid_attributes
      get :show, {:id => about_page.to_param}, valid_session
      expect(assigns(:about_page)).to eq(about_page)
    end
  end

  describe "GET new" do
    it "assigns a new about_page as @about_page" do
      get :new, {}, valid_session
      expect(assigns(:about_page)).to be_a_new(AboutPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested about_page as @about_page" do
      about_page = AboutPage.create! valid_attributes
      get :edit, {:id => about_page.to_param}, valid_session
      expect(assigns(:about_page)).to eq(about_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AboutPage" do
        expect {
          post :create, {:about_page => valid_attributes}, valid_session
        }.to change(AboutPage, :count).by(1)
      end

      it "assigns a newly created about_page as @about_page" do
        post :create, {:about_page => valid_attributes}, valid_session
        expect(assigns(:about_page)).to be_a(AboutPage)
        expect(assigns(:about_page)).to be_persisted
      end

      it "redirects to the created about_page" do
        post :create, {:about_page => valid_attributes}, valid_session
        expect(response).to redirect_to(AboutPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved about_page as @about_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        AboutPage.any_instance.stub(:save).and_return(false)
        post :create, {:about_page => {  }}, valid_session
        expect(assigns(:about_page)).to be_a_new(AboutPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AboutPage.any_instance.stub(:save).and_return(false)
        post :create, {:about_page => {  }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested about_page" do
        about_page = AboutPage.create! valid_attributes
        # Assuming there are no other about_pages in the database, this
        # specifies that the AboutPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(AboutPage).to receive(:update).with({ "these" => "params" })
        put :update, {:id => about_page.to_param, :about_page => { "these" => "params" }}, valid_session
      end

      it "assigns the requested about_page as @about_page" do
        about_page = AboutPage.create! valid_attributes
        put :update, {:id => about_page.to_param, :about_page => valid_attributes}, valid_session
        expect(assigns(:about_page)).to eq(about_page)
      end

      it "redirects to the about_page" do
        about_page = AboutPage.create! valid_attributes
        put :update, {:id => about_page.to_param, :about_page => valid_attributes}, valid_session
        expect(response).to redirect_to(about_page)
      end
    end

    describe "with invalid params" do
      it "assigns the about_page as @about_page" do
        about_page = AboutPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AboutPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => about_page.to_param, :about_page => {  }}, valid_session
        expect(assigns(:about_page)).to eq(about_page)
      end

      it "re-renders the 'edit' template" do
        about_page = AboutPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AboutPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => about_page.to_param, :about_page => {  }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested about_page" do
      about_page = AboutPage.create! valid_attributes
      expect {
        delete :destroy, {:id => about_page.to_param}, valid_session
      }.to change(AboutPage, :count).by(-1)
    end

    it "redirects to the about_pages list" do
      about_page = AboutPage.create! valid_attributes
      delete :destroy, {:id => about_page.to_param}, valid_session
      expect(response).to redirect_to(about_pages_url)
    end
  end

end
